### ISSUE TITLE
could you add the module fscache by default in kconfig?

### ISSUE THREAD

**Issue by fnordism** [Locietta/xanmod-kernel-WSL2#103]
I'm mounting some NFS shares under WSL. It would be great if they could also be cached under Windows using WSL and cachefilesd, just like on my other Linux machines.

**Comment by Locietta** [comment]
👉 https://github.com/Locietta/xanmod-kernel-WSL2/releases/tag/6.12.5-locietta-WSL2-xanmod1.3
