### ISSUE TITLE
WSL2 no longer loads when kernel version > 6.1.10 is used

### ISSUE THREAD

**Issue by taalojarvi** [Locietta/xanmod-kernel-WSL2#28]
I recently updated the kernel and found out that it does not boot anymore. I triaged the issue and found out that versions of kernel subsetquent to 6.1.10 no longer boot and produce the error code "Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT". 

I'll be happy to provide logs upon request

**Comment by Locietta** [comment]
Thanks for reporting it, I just also noticed this issue. I tried building kernel with clang 15.0.6 locally and it seems ok.

I've opened a PR to roll back LLVM version, can you try kernel image in https://github.com/Locietta/xanmod-kernel-WSL2/actions/runs/4199833705 to see if it works?

**Comment by jfdtse** [comment]
> 

This version works. Thank you

**Comment by Locietta** [comment]
I've published a [new release](https://github.com/Locietta/xanmod-kernel-WSL2/releases/tag/6.1.12-locietta-WSL2-xanmod1.2), feel free to reopen it if the issue persists.
