### ISSUE TITLE
WSL2 no longer loads when kernel version >6.2.1 is used

### ISSUE THREAD

**Issue by schuettecarsten** [Locietta/xanmod-kernel-WSL2#30]
WSL2 no longer loads when kernel version >6.2.1 is used.
No error is shown:

![image](https://user-images.githubusercontent.com/1275166/221806660-2986898d-1031-4b8a-ac34-2587f96f1d7c.png)

After some minutes, I get:

```Error code: Wsl/Service/CreateInstance/CreateVm/HCS_E_CONNECTION_TIMEOUT```

**Comment by Locietta** [comment]
Same symptom as #28, not sure what causes it this time... (clang/LTO I suspect though)

Being busy these days, I may look into it sometime later this week. Meanwhile, you probably have to stay at 6.1.x

For scoop installation, this can be done via `scoop reset xanmod-WSL2@6.1.14-1.1`

**Comment by Locietta** [comment]
Hello, could you test latest pre-release at https://github.com/Locietta/xanmod-kernel-WSL2/releases/tag/6.2.2-locietta-WSL2-xanmod1.2?

**Comment by schuettecarsten** [comment]
Works.

```
PS D:\> wsl uname -a
Linux laptopc3253 6.2.2-locietta-WSL2-xanmod1 #1 SMP Sat Mar  4 11:03:36 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
