### ISSUE TITLE
xanmod-WSL2-lts 6.1.70-1.1 didn't work

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Locietta/xanmod-kernel-WSL2#45]
First I tried the xanmod-WSL2-lts 6.1.70-1.1 Installed via Scoop and WSL2 didn't work (Error code: Wsl/Service/CreateInstance/MountVhd/HCS/0x80370110)

With the xanmod-WSL2 6.6.9-1.1 it works as described.

I tried again switch to LTS kernel and it failed again.
 

I chose the LTS version mainly because I guessed, it should be more stable than recent.
Thanks for this project.

**Comment by Locietta** [comment]
Thanks for reporting the issue!

I can confirm LTS build is broken, but I get a different error code (Wsl/Service/CreateInstance/CreateVm/0x80072746). Can you share your WSL version (via `wsl --version`) and configurations in `.wslconfig` and `wsl.conf`?

The last working lts build for me is 6.1.49, I'm not sure if that's the same case for you.

**Comment by Locietta** [comment]
The naming for LTS/Stable just reflects what they're called at Xanmod upstream, and LTS doesn't imply more stability than Latest. In fact, the LTS build was PR'd(@dingdang66686) later, and I personally only use the latest, so the latest is actually more stable...

Sorry for the confusion, maybe I should add the situation to readme.

**Comment by Locietta** [comment]
LTS is now at 6.6, and it's working fine, so closing this issue :)
