### ISSUE TITLE
Provide Update Tool

### ISSUE THREAD

**Issue by Locietta** [Locietta/xanmod-kernel-WSL2#5]
Provide a updater script which can automatically update the kernel.

It can be easy, just do what we've done in CI in a bash script. Will do if I have time ( ´ー`)

**Comment by Locietta** [comment]
Making a Scoop bucket seems like a better solution 🤔

**Comment by taalojarvi** [comment]
I have written a small script to update the kernel when a new build is out. Pull requests would be welcome

Link: https://github.com/taalojarvi/scripts/blob/main/wsl_updater.sh

**Comment by Locietta** [comment]
I've added manifests for the kernel in my personal scoop bucket at Locietta/sniffer@484c73a

install and update the kernel will look like this:
```
scoop bucket add sniffer https://github.com/Locietta/sniffer
scoop install xanmod-WSL2
# scoop install xanmod-WSL2-skylake

# to update everything installed by scoop
scoop update * 
```

And I'll update readme to include @taalojarvi's script (thanks for your script!) and my scoop bucket.
