### ISSUE TITLE
Backport Upstream linux-msft-wsl Kernel Options

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Locietta/xanmod-kernel-WSL2#58]
I tried to use [kernel features](https://github.com/Locietta/xanmod-kernel-WSL2/issues/46) that were present in the Microsoft WSL2-Linux-Kernel but found them missing in xanmod wsl2 kernel.

Can we backport kernel config from upstream to not missing out wsl2 default features and apply xanmod options on top of that?

https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.15.y/arch/x86/configs/config-wsl
https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.1.y/arch/x86/configs/config-wsl

_In the meantime, I build my own kernel with enabled CONFIG flags, works for me._

**Comment by Locietta** [comment]
Thanks for reporting. I will re-merge the config files.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Plan merging wsl2_defconfig with [config-wsl](https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-6.1.y/arch/x86/configs/config-wsl) 6.1.y or [config-wsl](https://github.com/microsoft/WSL2-Linux-Kernel/blob/linux-msft-wsl-5.15.y/arch/x86/configs/config-wsl) 5.15.y ?

**Comment by Locietta** [comment]
With 5.15.y, as the 6.1.y config is not getting update for around a year.
