### ISSUE TITLE
Feature Request: CFI

### ISSUE THREAD

**Issue by Andarwinux** [Locietta/xanmod-kernel-WSL2#61]
Hi,
can you add a kernel build of CFI and CET?
just CFI_CLANG,X86_USER_SHADOW_STACK,X86_KERNEL_IBT.

**Comment by Locietta** [comment]
The kernel was built with IBT enabled, but one day it caused WSL2 unbootable, so it was disabled at #32. I think I tried CFI and CET  before and got similar result.

I just quickly revisit the build with all your 3 configs on, and sadly, WSL2 fails to boot with that kernel build. It's been sad that many kernel hardening feature just cause WSL2 to not boot. I'd like to add these in a clang-built kernel, but it just breaks :disappointed:

**Comment by Locietta** [comment]
I've opened a PR(#62) to re-enable CFI & CET.
