### ISSUE TITLE
Docker Desktop Incompatibility with 6.8.10-locietta-WSL2-xanmod1.1 Kernel

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Locietta/xanmod-kernel-WSL2#64]
Docker Desktop fails to function correctly when running on the 6.8.10-locietta-WSL2-xanmod1.1 kernel. Users attempting to utilize Docker Desktop in conjunction with this kernel are experiencing operational issues that prevent Docker Desktop from starting its engine at all.

Steps to Reproduce:

1. Install the 6.8.10-locietta-WSL2-xanmod1.1 kernel on a Windows Subsystem for Linux 2 (WSL2) environment.
2. Install Docker Desktop on the same environment.
3. Attempt to launch Docker Desktop WSL2 integrated and observe its functionality.

Docker Desktop fails to launch This include failure to start the Docker daemon, or other critical errors that impede functionality.

Workaround:
As a temporary workaround, users can install and use Docker Community Edition (docker-ce) directly within the WSL2 distribution instead of relying on Docker Desktop. This involves the following steps:

-  Ensure the xanmod1.1 kernel is installed and running.
-  Install docker-ce within the WSL2 distribution by following the official Docker installation guide for Linux.
-  Use docker-ce for container management and other Docker operations.

Environment:

-  Windows Version: 11x64
-  WSL2 Kernel Version: 6.8.10-locietta-WSL2-xanmod1.1
-  Docker Desktop Version: 26.1.1

Additional Information:

Docker Desktop system information outputs.

```bash
docker info
Client:
 Version:    26.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.29
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.8.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe
```

**Comment by stevenhobs** [comment]
Is this could be fix?

**Comment by nexplorer-3e** [comment]
same here:
`Linux TN-Rutalko 6.9.9-locietta-WSL2-xanmod1 #1 SMP Fri Jul 12 06:49:18 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
does there exists any workaround here?
